import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Providers from "./lib/Providers";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import MaxWidthRappers from "@/components/MaxWidthRapper";
import Bottom from "./Components/bottom";
import Lefttab from "./Components/lefttab";
import Navbar from "./Components/Navbar";
import Head from "next/head";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Green feature",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
        <script
          src="https://checkout.razorpay.com/v1/checkout.js"
          async
        ></script>
      </Head> */}
      <body className="min-h-screen bg-background font-sans antialiased">
        <Providers>
          <Toaster />
          <MaxWidthRappers>
            <div>
              <Navbar />
              <main className="flex flex-col md:flex-row w-full overflow-hidden">
                {/* Left */}
                <div className="hidden md:flex md:fixed md:h-full md:w-64">
                  <Lefttab />
                </div>

                {/* Middle */}
                <div className="flex-grow md:ml-56">{children}</div>

                {/* Bottom */}
                <div className="md:hidden fixed bottom-0 w-full bg-white z-10">
                  <Bottom />
                </div>
              </main>
            </div>
          </MaxWidthRappers>
        </Providers>
      </body>
    </html>
  );
}
