export const states = [
  // States (28)
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",

  // Union Territories (8)
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
const districtsByState: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur district",
    "Chittoor district",
    "East Godavari district",
    "Guntur district",
    "Krishna district",
    "Kurnool district",
    "Nellore district",
    "Prakasam district",
    "Srikakulam district",
    "Visakhapatnam district",
    "Vizianagaram district",
    "West Godavari district",
    "YSR Kadapa district",
  ],
  "Arunachal Pradesh": [
    "Anjaw district",
    "Changlang district",
    "Dibang Valley district",
    "East Kameng district",
    "East Siang district",
    "Kamle district",
    "Kra Daadi district",
    "Kurung Kumey district",
    "Lepa Rada district",
    "Lohit district",
    "Longding district",
    "Lower Dibang Valley district",
    "Lower Siang district",
    "Lower Subansiri district",
    "Namsai district",
    "Pakke Kessang district",
    "Papum Pare district",
    "Shi Yomi district",
    "Siang district",
    "Tawang district",
    "Tirap district",
    "Upper Siang district",
    "Upper Subansiri district",
    "West Kameng district",
    "West Siang district",
  ],
  Assam: [
    "Baksa district",
    "Barpeta district",
    "Biswanath district",
    "Bongaigaon district",
    "Cachar district",
    "Charaideo district",
    "Chirang district",
    "Darrang district",
    "Dhemaji district",
    "Dhubri district",
    "Dibrugarh district",
    "Dima Hasao district",
    "Goalpara district",
    "Golaghat district",
    "Hailakandi district",
    "Hojai district",
    "Jorhat district",
    "Kamrup district",
    "Kamrup Metropolitan district",
    "Karbi Anglong district",
    "Karimganj district",
    "Kokrajhar district",
    "Lakhimpur district",
    "Majuli district",
    "Morigaon district",
    "Nagaon district",
    "Nalbari district",
    "Sivasagar district",
    "Sonitpur district",
    "South Salmara-Mankachar district",
    "Tinsukia district",
    "Udalguri district",
    "West Karbi Anglong district",
  ],
  Bihar: [
    "Araria district",
    "Arwal district",
    "Aurangabad district",
    "Banka district",
    "Begusarai district",
    "Bhagalpur district",
    "Bhojpur district",
    "Buxar district",
    "Darbhanga district",
    "East Champaran district",
    "Gaya district",
    "Gopalganj district",
    "Jamui district",
    "Jehanabad district",
    "Kaimur district",
    "Katihar district",
    "Khagaria district",
    "Kishanganj district",
    "Lakhisarai district",
    "Madhepura district",
    "Madhubani district",
    "Munger district",
    "Muzaffarpur district",
    "Nalanda district",
    "Nawada district",
    "Patna district",
    "Purnia district",
    "Rohtas district",
    "Saharsa district",
    "Samastipur district",
    "Saran district",
    "Sheikhpura district",
    "Sheohar district",
    "Sitamarhi district",
    "Siwan district",
    "Supaul district",
    "Vaishali district",
    "West Champaran district",
  ],
  Chhattisgarh: [
    "Balod district",
    "Baloda Bazar district",
    "Balrampur district",
    "Bastar district",
    "Bemetara district",
    "Bijapur district",
    "Bilaspur district",
    "Dantewada district",
    "Dhamtari district",
    "Durg district",
    "Gariaband district",
    "Janjgir-Champa district",
    "Jashpur district",
    "Kabirdham district",
    "Kanker district",
    "Kondagaon district",
    "Korba district",
    "Koriya district",
    "Mahasamund district",
    "Mungeli district",
    "Narayanpur district",
    "Raigarh district",
    "Raipur district",
    "Rajnandgaon district",
    "Sukma district",
    "Surajpur district",
    "Surguja district",
  ],
  Goa: ["North Goa district", "South Goa district"],
  Gujarat: [
    "Ahmedabad district",
    "Amreli district",
    "Anand district",
    "Aravalli district",
    "Banaskantha district",
    "Bharuch district",
    "Bhavnagar district",
    "Botad district",
    "Chhota Udaipur district",
    "Dahod district",
    "Dang district",
    "Devbhoomi Dwarka district",
    "Gandhinagar district",
    "Gir Somnath district",
    "Jamnagar district",
    "Junagadh district",
    "Kheda district",
    "Kutch district",
    "Mahisagar district",
    "Mehsana district",
    "Morbi district",
    "Narmada district",
    "Navsari district",
    "Panchmahal district",
    "Patan district",
    "Porbandar district",
    "Rajkot district",
    "Sabarkantha district",
    "Surat district",
    "Surendranagar district",
    "Tapi district",
    "Vadodara district",
    "Valsad district",
  ],
  Haryana: [
    "Ambala district",
    "Bhiwani district",
    "Charkhi Dadri district",
    "Faridabad district",
    "Fatehabad district",
    "Gurugram district",
    "Hisar district",
    "Jhajjar district",
    "Jind district",
    "Kaithal district",
    "Karnal district",
    "Kurukshetra district",
    "Mahendragarh district",
    "Nuh district",
    "Palwal district",
    "Panchkula district",
    "Panipat district",
    "Rewari district",
    "Rohtak district",
    "Sirsa district",
    "Sonipat district",
    "Yamunanagar district",
  ],
  "Himachal Pradesh": [
    "Bilaspur district",
    "Chamba district",
    "Hamirpur district",
    "Kangra district",
    "Kinnaur district",
    "Kullu district",
    "Lahaul and Spiti district",
    "Mandi district",
    "Shimla district",
    "Sirmaur district",
    "Solan district",
    "Una district",
  ],
  Jharkhand: [
    "Bokaro district",
    "Chatra district",
    "Deoghar district",
    "Dhanbad district",
    "Dumka district",
    "East Singhbhum district",
    "Garhwa district",
    "Giridih district",
    "Godda district",
    "Gumla district",
    "Hazaribagh district",
    "Jamtara district",
    "Khunti district",
    "Koderma district",
    "Latehar district",
    "Lohardaga district",
    "Pakur district",
    "Palamu district",
    "Ramgarh district",
    "Ranchi district",
    "Sahebganj district",
    "Seraikela Kharsawan district",
    "Simdega district",
    "West Singhbhum district",
  ],
  Karnataka: [
    "Bagalkot district",
    "Ballari district",
    "Belagavi district",
    "Bengaluru Rural district",
    "Bengaluru Urban district",
    "Bidar district",
    "Chamarajanagar district",
    "Chikkaballapur district",
    "Chikkamagaluru district",
    "Chitradurga district",
    "Dakshina Kannada district",
    "Davanagere district",
    "Dharwad district",
    "Gadag district",
    "Hassan district",
    "Haveri district",
    "Kalaburagi district",
    "Kodagu district",
    "Kolar district",
    "Koppal district",
    "Mandya district",
    "Mysuru district",
    "Raichur district",
    "Ramanagara district",
    "Shivamogga district",
    "Tumakuru district",
    "Udupi district",
    "Uttara Kannada district",
    "Vijayapura district",
    "Yadgir district",
  ],
  Kerala: [
    "Alappuzha district",
    "Ernakulam district",
    "Idukki district",
    "Kannur district",
    "Kasaragod district",
    "Kollam district",
    "Kottayam district",
    "Kozhikode district",
    "Malappuram district",
    "Palakkad district",
    "Pathanamthitta district",
    "Thiruvananthapuram district",
    "Thrissur district",
    "Wayanad district",
  ],
  "Madhya Pradesh": [
    "Agar Malwa district",
    "Alirajpur district",
    "Anuppur district",
    "Ashoknagar district",
    "Balaghat district",
    "Barwani district",
    "Betul district",
    "Bhind district",
    "Bhopal district",
    "Burhanpur district",
    "Chhatarpur district",
    "Chhindwara district",
    "Damoh district",
    "Datia district",
    "Dewas district",
    "Dhar district",
    "Dindori district",
    "Guna district",
    "Gwalior district",
    "Harda district",
    "Hoshangabad district",
    "Indore district",
    "Jabalpur district",
    "Jhabua district",
    "Katni district",
    "Khandwa district",
    "Khargone district",
    "Maihar district",
    "Mandla district",
    "Mandsaur district",
    "Morena district",
    "Narsinghpur district",
    "Neemuch district",
    "Niwari district",
    "Panna district",
    "Raisen district",
    "Rajgarh district",
    "Ratlam district",
    "Rewa district",
    "Sagar district",
    "Satna district",
    "Sehore district",
    "Seoni district",
    "Shahdol district",
    "Shajapur district",
    "Sheopur district",
    "Shivpuri district",
    "Sidhi district",
    "Singrauli district",
    "Tikamgarh district",
    "Ujjain district",
    "Umaria district",
    "Vidisha district",
  ],
  Maharashtra: [
    "Ahmednagar district",
    "Akola district",
    "Amravati district",
    "Aurangabad district",
    "Beed district",
    "Bhandara district",
    "Buldhana district",
    "Chandrapur district",
    "Dhule district",
    "Gadchiroli district",
    "Gondia district",
    "Hingoli district",
    "Jalgaon district",
    "Jalna district",
    "Kolhapur district",
    "Latur district",
    "Mumbai City district",
    "Mumbai Suburban district",
    "Nagpur district",
    "Nanded district",
    "Nandurbar district",
    "Nashik district",
    "Osmanabad district",
    "Palghar district",
    "Parbhani district",
    "Pune district",
    "Raigad district",
    "Ratnagiri district",
    "Sangli district",
    "Satara district",
    "Sindhudurg district",
    "Solapur district",
    "Thane district",
    "Wardha district",
    "Washim district",
    "Yavatmal district",
  ],
  Manipur: [
    "Bishnupur district",
    "Chandel district",
    "Churachandpur district",
    "Imphal East district",
    "Imphal West district",
    "Jiribam district",
    "Kakching district",
    "Kamjong district",
    "Kangpokpi district",
    "Noney district",
    "Pherzawl district",
    "Senapati district",
    "Tamenglong district",
    "Tengnoupal district",
    "Thoubal district",
    "Ukhrul district",
  ],
  Meghalaya: [
    "East Garo Hills district",
    "East Jaintia Hills district",
    "East Khasi Hills district",
    "North Garo Hills district",
    "Ri-Bhoi district",
    "South Garo Hills district",
    "South West Garo Hills district",
    "South West Khasi Hills district",
    "West Garo Hills district",
    "West Jaintia Hills district",
    "West Khasi Hills district",
  ],
  Mizoram: [
    "Aizawl district",
    "Champhai district",
    "Hnahthial district",
    "Khawzawl district",
    "Kolasib district",
    "Lawngtlai district",
    "Lunglei district",
    "Mamit district",
    "Saiha district",
    "Saitual district",
    "Serchhip district",
  ],
  Nagaland: [
    "Chümoukedima district",
    "Dimapur district",
    "Kiphire district",
    "Kohima district",
    "Longleng district",
    "Mokokchung district",
    "Mon district",
    "Niuland district",
    "Noklak district",
    "Peren district",
    "Phek district",
    "Shamator district",
    "Tseminyü district",
    "Tuensang district",
    "Wokha district",
    "Zünheboto district",
  ],
  Odisha: [
    "Angul district",
    "Balangir district",
    "Balasore district",
    "Bargarh district",
    "Bhadrak district",
    "Boudh district",
    "Cuttack district",
    "Deogarh district",
    "Dhenkanal district",
    "Gajapati district",
    "Ganjam district",
    "Jagatsinghpur district",
    "Jajpur district",
    "Jharsuguda district",
    "Kalahandi district",
    "Kandhamal district",
    "Kendrapara district",
    "Kendujhar district",
    "Khordha district",
    "Koraput district",
    "Malkangiri district",
    "Mayurbhanj district",
    "Nabarangpur district",
    "Nayagarh district",
    "Nuapada district",
    "Puri district",
    "Rayagada district",
    "Sambalpur district",
    "Subarnapur district",
    "Sundargarh district",
  ],
  Punjab: [
    "Amritsar district",
    "Barnala district",
    "Bathinda district",
    "Faridkot district",
    "Fatehgarh Sahib district",
    "Fazilka district",
    "Ferozepur district",
    "Gurdaspur district",
    "Hoshiarpur district",
    "Jalandhar district",
    "Kapurthala district",
    "Ludhiana district",
    "Mansa district",
    "Moga district",
    "Muktsar district",
    "Pathankot district",
    "Patiala district",
    "Rupnagar district",
    "Sangrur district",
    "SAS Nagar district",
    "SBS Nagar district",
    "Tarn Taran district",
  ],
  Rajasthan: [
    "Ajmer district",
    "Alwar district",
    "Banswara district",
    "Baran district",
    "Barmer district",
    "Bharatpur district",
    "Bhilwara district",
    "Bikaner district",
    "Bundi district",
    "Chittorgarh district",
    "Churu district",
    "Dausa district",
    "Dholpur district",
    "Dungarpur district",
    "Hanumangarh district",
    "Jaipur district",
    "Jaisalmer district",
    "Jalor district",
    "Jhalawar district",
    "Jhunjhunu district",
    "Jodhpur district",
    "Karauli district",
    "Kota district",
    "Nagaur district",
    "Pali district",
    "Pratapgarh district",
    "Rajsamand district",
    "Sawai Madhopur district",
    "Sikar district",
    "Sirohi district",
    "Sri Ganganagar district",
    "Tonk district",
    "Udaipur district",
  ],
  Sikkim: [
    "East Sikkim district",
    "North Sikkim district",
    "South Sikkim district",
    "West Sikkim district",
  ],
  "Tamil Nadu": [
    "Ariyalur district",
    "Chengalpattu district",
    "Chennai district",
    "Coimbatore district",
    "Cuddalore district",
    "Dharmapuri district",
    "Dindigul district",
    "Erode district",
    "Kallakurichi district",
    "Kanchipuram district",
    "Kanyakumari district",
    "Karur district",
    "Krishnagiri district",
    "Madurai district",
    "Mayiladuthurai district",
    "Nagapattinam district",
    "Namakkal district",
    "Nilgiris district",
    "Perambalur district",
    "Pudukkottai district",
    "Ramanathapuram district",
    "Ranipet district",
    "Salem district",
    "Sivaganga district",
    "Tenkasi district",
    "Thanjavur district",
    "Theni district",
    "Thoothukudi district",
    "Tiruchirappalli district",
    "Tirunelveli district",
    "Tirupathur district",
    "Tiruppur district",
    "Tiruvallur district",
    "Tiruvannamalai district",
    "Tiruvarur district",
    "Vellore district",
    "Viluppuram district",
    "Virudhunagar district",
  ],
  Telangana: [
    "Adilabad district",
    "Bhadradri Kothagudem district",
    "Hyderabad district",
    "Jagtial district",
    "Jangaon district",
    "Jayashankar Bhupalpally district",
    "Jogulamba Gadwal district",
    "Kamareddy district",
    "Karimnagar district",
    "Khammam district",
    "Komaram Bheem district",
    "Mahabubabad district",
    "Mahabubnagar district",
    "Mancherial district",
    "Medak district",
    "Medchal–Malkajgiri district",
    "Mulugu district",
    "Nagarkurnool district",
    "Nalgonda district",
    "Narayanpet district",
    "Nirmal district",
    "Nizamabad district",
    "Peddapalli district",
    "Rajanna Sircilla district",
    "Rangareddy district",
    "Sangareddy district",
    "Siddipet district",
    "Suryapet district",
    "Vikarabad district",
    "Wanaparthy district",
    "Warangal district",
    "Yadadri Bhuvanagiri district",
  ],
  Tripura: [
    "Dhalai district",
    "Gomati district",
    "Khowai district",
    "North Tripura district",
    "Sepahijala district",
    "South Tripura district",
    "Unakoti district",
    "West Tripura district",
  ],
  "Uttar Pradesh": [
    "Agra district",
    "Aligarh district",
    "Ambedkar Nagar district",
    "Amethi district",
    "Amroha district",
    "Auraiya district",
    "Ayodhya district",
    "Azamgarh district",
    "Baghpat district",
    "Bahraich district",
    "Ballia district",
    "Balrampur district",
    "Banda district",
    "Barabanki district",
    "Bareilly district",
    "Basti district",
    "Bhadohi district",
    "Bijnor district",
    "Budaun district",
    "Bulandshahr district",
    "Chandauli district",
    "Chitrakoot district",
    "Deoria district",
    "Etah district",
    "Etawah district",
    "Farrukhabad district",
    "Fatehpur district",
    "Firozabad district",
    "Gautam Buddha Nagar district",
    "Ghaziabad district",
    "Ghazipur district",
    "Gonda district",
    "Gorakhpur district",
    "Hamirpur district",
    "Hapur district",
    "Hardoi district",
    "Hathras district",
    "Jalaun district",
    "Jaunpur district",
    "Jhansi district",
    "Kannauj district",
    "Kanpur Dehat district",
    "Kanpur Nagar district",
    "Kasganj district",
    "Kaushambi district",
    "Kushinagar district",
    "Lakhimpur Kheri district",
    "Lalitpur district",
    "Lucknow district",
    "Maharajganj district",
    "Mahoba district",
    "Mainpuri district",
    "Mathura district",
    "Mau district",
    "Meerut district",
    "Mirzapur district",
    "Moradabad district",
    "Muzaffarnagar district",
    "Pilibhit district",
    "Pratapgarh district",
    "Prayagraj district",
    "Raebareli district",
    "Rampur district",
    "Saharanpur district",
    "Sambhal district",
    "Sant Kabir Nagar district",
    "Shahjahanpur district",
    "Shamli district",
    "Shravasti district",
    "Siddharthnagar district",
    "Sitapur district",
    "Sonbhadra district",
    "Sultanpur district",
    "Unnao district",
    "Varanasi district",
  ],
  Uttarakhand: [
    "Almora district",
    "Bageshwar district",
    "Chamoli district",
    "Champawat district",
    "Dehradun district",
    "Haridwar district",
    "Nainital district",
    "Pauri Garhwal district",
    "Pithoragarh district",
    "Rudraprayag district",
    "Tehri Garhwal district",
    "Udham Singh Nagar district",
    "Uttarkashi district",
  ],
  "West Bengal": [
    "Alipurduar district",
    "Bankura district",
    "Cooch Behar district",
    "Dakshin Dinajpur district",
    "Darjeeling district",
    "Hooghly district",
    "Howrah district",
    "Jalpaiguri district",
    "Jhargram district",
    "Kalimpong district",
    "Kolkata district",
    "Malda district",
    "Murshidabad district",
    "Nadia district",
    "North 24 Parganas district",
    "Paschim Bardhaman district",
    "Paschim Medinipur district",
    "Purba Bardhaman district",
    "Purba Medinipur district",
    "Purulia district",
    "South 24 Parganas district",
    "Uttar Dinajpur district",
  ],
  "Andaman and Nicobar Islands": [
    "Nicobar district",
    "North and Middle Andaman district",
    "South Andaman district",
  ],
  Chandigarh: ["Chandigarh district"],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Dadra and Nagar Haveli district",
    "Daman district",
    "Diu district",
  ],
  Delhi: [
    "Central Delhi district",
    "East Delhi district",
    "New Delhi district",
    "North Delhi district",
    "North East Delhi district",
    "North West Delhi district",
    "Shahdara district",
    "South Delhi district",
    "South East Delhi district",
    "South West Delhi district",
    "West Delhi district",
  ],
  "Jammu and Kashmir": [
    "Anantnag district",
    "Bandipora district",
    "Baramulla district",
    "Budgam district",
    "Doda district",
    "Ganderbal district",
    "Jammu district",
    "Kathua district",
    "Kishtwar district",
    "Kulgam district",
    "Kupwara district",
    "Poonch district",
    "Pulwama district",
    "Rajouri district",
    "Ramban district",
    "Reasi district",
    "Samba district",
    "Shopian district",
    "Srinagar district",
    "Udhampur district",
  ],
  Ladakh: ["Kargil district", "Leh district"],
  Lakshadweep: ["Lakshadweep district"],
  Puducherry: [
    "Karaikal district",
    "Mahe district",
    "Puducherry district",
    "Yanam district",
  ],
};

export default districtsByState;
